In [42]:
import requests
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)
pd.set_option('display.float_format', lambda x: '%.3f' % x)


url = "https://data.wa.gov/resource/ijvn-uemp.json"

params = {
    "$where": "lower(awarding_agency_name) like '%bellevue, city of%'",
    "$limit": 50000,
    "$offset": 0
}

rows = []

while True:
    response = requests.get(url, params=params)
    response.raise_for_status()
    batch = response.json()
    
    if not batch:
        break
    
    rows.extend(batch)
    params["$offset"] += params["$limit"]

df_PWProjects = pd.DataFrame(rows)

In [43]:
df_PWProjects.head(8)

,project_id,awarding_agency_name,agency_category_type,prime_contractor_name,prime_contractor_ubi,prime_intent_id,project_name,contract_number,_apprentice_utilization_,journeylevel_hours,apprentice_hours,total_hours,apprentice_wages,journeylevel_wages,total_wages,female_hours,female_utilization_percentage,minority_hours,minority_utilization,veteran_hours,veteran_utilization_percentage,asbestos_abatement_workers,boilermakers,bricklayers_marble_masons,brick_and_marble_masons,brick_mason,building_service_employees,cabinet_makers_in_shop,carpenters,cement_masons,divers_tenders,dredge_workers,drywall_applicator,drywall_tapers,electrical_fixture_maintenance,electricians_inside,electricians_motor_shop,electricians_powerline,elevator_constructors,electronic_technicians,electronic_telecommunication,fabricated_precast_concrete,fence_erectors,flaggers,glaziers,heat_frost_insulators_and,heating_equipment_mechanics,hod_carriers_mason_tenders,industrial_engine_and_machine,industrial_power_vacuum,inland_boatmen,inspection_cleaning_sealing,inspection_cleaning_sealing_1,insulation_applicators,ironworkers,laborers,laborers_underground_sewer,landscape_construction,landscape_maintenance,lathers,machinists_hydroelectric,marble_setters,metal_fabrication_in_shop,millwright,modular_buildings,painters,pile_driver,plasterers,playground_park_equipment,plumbers_pipefitters,power_equipment_operators,power_equipment_operators_1,power_line_clearance_tree,residential_brick_mason,refrigeration_air_conditioning,residential_drywall,residential_brick_marble,residential_carpenters,residential_drywall_tapers,residential_electricians,residential_electronic,residential_glaziers,residential_insulation,residential_laborers,residential_cement_masons,residential_marble_setters,residential_stone_masons,residential_painters,residential_plumbers,residential_refrigeration,residential_sheet_metal,residential_soft_floor_layers,residential_sprinkler_fitters,residential_terrazzo_tile,residential_terrazzo_tile_1,residential_tile_setters,residential_terrazzo_workers,roofers,sheet_metal_workers,shipbuilding_ship_repair,sign_makers_installers,sign_makers_installers_non,soft_floor_layers,solar_controls_for_windows,sprinkler_fitters_fire,stage_rigging_mechanics_non,stone_masons,street_and_parking_lot_sweeper,surveyors,telecommunication_technicians,telephone_line_construction,terrazzo_workers,tile_marble_terrazzo_finishers,tile_setters,traffic_control_stripers,truck_drivers,truck_drivers_ready_mix,well_drillers_irrigation
0,1045705,"BELLEVUE, CITY OF",City,SIGNATURE LANDSCAPE SVCS LLC,603498589,1291237,COB Hillaire invasives per Andy Heider,139307,0,60,0,60,0,1624,1624,0,0,32,53.33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1109031,"BELLEVUE, CITY OF",City,FASTSIGNS OF BELLEVUE,603160830,1400519,Mini CH-Removal of Existing Sign,36216,0,3,0,3,0,270,270,0,0,3,100,3,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,902077,"BELLEVUE, CITY OF",City,PRIME ELECTRIC INC,601004783,1027045,Lakemont Snowcam,3001425,33.33,12,6,18,557.64,1185.66,1743.3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1041074,"BELLEVUE, CITY OF",City,SIGNATURE LANDSCAPE SVCS LLC,603498589,1283923,COB Replace centers in pots per Andrew Heider,136086,0,6,0,6,0,159,159,0,0,3,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,907867,"BELLEVUE, CITY OF/ PARKS & REC",City,ROBERT CARRILLO ENT LLC,604265515,1037396,NEWCASTLE BEACH PARK,PO 24550,0,18,0,18,0,915.48,915.48,0,0,18,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,996974,"BELLEVUE, CITY OF",City,SKYLINE LANDSCAPE LLC,603018209,1207257,116th Overlake POC Retro,29779,0,24,0,24,0,1032.96,1032.96,0,0,24,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1209630,"BELLEVUE, CITY OF",City,INTERIOR CONTRACTING SERV LLC,605274751,1581825,CIty Hall,137370,0,51.75,0,51.75,0,3366.34,3366.34,0,0,6.5,12.56,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,1073768,"BELLEVUE, CITY OF",City,MCKINSTRY CO LLC,602569922,1337940,2023 - Deficiency Repairs - Add Missing Signag...,WO 9915529,0,8,0,8,0,760.72,760.72,0,0,4,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0

In [44]:
df_PWProjects.count()

project_id                        5992
awarding_agency_name              5992
agency_category_type              5991
prime_contractor_name             5992
prime_contractor_ubi              5992
prime_intent_id                   5992
project_name                      5988
contract_number                   5864
_apprentice_utilization_          2713
journeylevel_hours                2715
apprentice_hours                  2715
total_hours                       5992
apprentice_wages                  2715
journeylevel_wages                2715
total_wages                       2715
female_hours                      5992
female_utilization_percentage     5992
minority_hours                    5992
minority_utilization              5992
veteran_hours                     5992
veteran_utilization_percentage    5992
asbestos_abatement_workers        5992
boilermakers                      5992
bricklayers_marble_masons         5992
brick_and_marble_masons           5992
brick_mason                       5992
building_service_employees        5992
cabinet_makers_in_shop            5992
carpenters                        5992
cement_masons                     5992
divers_tenders                    5992
dredge_workers                    5992
drywall_applicator                5992
drywall_tapers                    5992
electrical_fixture_maintenance    5992
electricians_inside               5992
electricians_motor_shop           5992
electricians_powerline            5992
elevator_constructors             5992
electronic_technicians            5992
electronic_telecommunication      5992
fabricated_precast_concrete       5992
fence_erectors                    5992
flaggers                          5992
glaziers                          5992
heat_frost_insulators_and         5992
heating_equipment_mechanics       5992
hod_carriers_mason_tenders        5992
industrial_engine_and_machine     5992
industrial_power_vacuum           5992
inland_boatmen                    5992
inspection_cleaning_sealing       5992
inspection_cleaning_sealing_1     5992
insulation_applicators            5992
ironworkers                       5992
laborers                          5992
laborers_underground_sewer        5992
landscape_construction            5992
landscape_maintenance             5992
lathers                           5992
machinists_hydroelectric          5992
marble_setters                    5992
metal_fabrication_in_shop         5992
millwright                        5992
modular_buildings                 5992
painters                          5992
pile_driver                       5992
plasterers                        5992
playground_park_equipment         5992
plumbers_pipefitters              5992
power_equipment_operators         5992
power_equipment_operators_1       5992
power_line_clearance_tree         5992
residential_brick_mason           5992
refrigeration_air_conditioning    5992
residential_drywall               5992
residential_brick_marble          5992
residential_carpenters            5992
residential_drywall_tapers        5992
residential_electricians          5992
residential_electronic            5992
residential_glaziers              5992
residential_insulation            5992
residential_laborers              5992
residential_cement_masons         5992
residential_marble_setters        5992
residential_stone_masons          5992
residential_painters              5992
residential_plumbers              5992
residential_refrigeration         5992
residential_sheet_metal           5992
residential_soft_floor_layers     5992
residential_sprinkler_fitters     5992
residential_terrazzo_tile         5992
residential_terrazzo_tile_1       5992
residential_tile_setters          5992
residential_terrazzo_workers      5992
roofers                           5992
sheet_metal_workers               5992
shipbuilding_ship_repair          5992
sign_makers_installers            5992
sign_makers_installers_non        5992
soft_floor_layers                 5992
solar_controls_for_windows        5992
sprinkler_fitters_fire            5992
stage_rigging_mechanics_non       5992
stone_masons                      5992
street_and_parking_lot_sweeper    5992
surveyors                         5992
telecommunication_technicians     5992
telephone_line_construction       5992
terrazzo_workers                  5992
tile_marble_terrazzo_finishers    5992
tile_setters                      5992
traffic_control_stripers          5992
truck_drivers                     5992
truck_drivers_ready_mix           5992
well_drillers_irrigation          5992
dtype: int64

In [63]:
pd.DataFrame(df_PWProjects.columns, columns=["Column Names"])

                       Column Names
0                        project_id
1              awarding_agency_name
2              agency_category_type
3             prime_contractor_name
4              prime_contractor_ubi
5                   prime_intent_id
6                      project_name
7                   contract_number
8          _apprentice_utilization_
9                journeylevel_hours
10                 apprentice_hours
11                      total_hours
12                 apprentice_wages
13               journeylevel_wages
14                      total_wages
15                     female_hours
16    female_utilization_percentage
17                   minority_hours
18             minority_utilization
19                    veteran_hours
20   veteran_utilization_percentage
21       asbestos_abatement_workers
22                     boilermakers
23        bricklayers_marble_masons
24          brick_and_marble_masons
25                      brick_mason
26       building_service_employees
27           cabinet_makers_in_shop
28                       carpenters
29                    cement_masons
30                   divers_tenders
31                   dredge_workers
32               drywall_applicator
33                   drywall_tapers
34   electrical_fixture_maintenance
35              electricians_inside
36          electricians_motor_shop
37           electricians_powerline
38            elevator_constructors
39           electronic_technicians
40     electronic_telecommunication
41      fabricated_precast_concrete
42                   fence_erectors
43                         flaggers
44                         glaziers
45        heat_frost_insulators_and
46      heating_equipment_mechanics
47       hod_carriers_mason_tenders
48    industrial_engine_and_machine
49          industrial_power_vacuum
50                   inland_boatmen
51      inspection_cleaning_sealing
52    inspection_cleaning_sealing_1
53           insulation_applicators
54                      ironworkers
55                         laborers
56       laborers_underground_sewer
57           landscape_construction
58            landscape_maintenance
59                          lathers
60         machinists_hydroelectric
61                   marble_setters
62        metal_fabrication_in_shop
63                       millwright
64                modular_buildings
65                         painters
66                      pile_driver
67                       plasterers
68        playground_park_equipment
69             plumbers_pipefitters
70        power_equipment_operators
71      power_equipment_operators_1
72        power_line_clearance_tree
73          residential_brick_mason
74   refrigeration_air_conditioning
75              residential_drywall
76         residential_brick_marble
77           residential_carpenters
78       residential_drywall_tapers
79         residential_electricians
80           residential_electronic
81             residential_glaziers
82           residential_insulation
83             residential_laborers
84        residential_cement_masons
85       residential_marble_setters
86         residential_stone_masons
87             residential_painters
88             residential_plumbers
89        residential_refrigeration
90          residential_sheet_metal
91    residential_soft_floor_layers
92    residential_sprinkler_fitters
93        residential_terrazzo_tile
94      residential_terrazzo_tile_1
95         residential_tile_setters
96     residential_terrazzo_workers
97                          roofers
98              sheet_metal_workers
99         shipbuilding_ship_repair
100          sign_makers_installers
101      sign_makers_installers_non
102               soft_floor_layers
103      solar_controls_for_windows
104          sprinkler_fitters_fire
105     stage_rigging_mechanics_non
106                    stone_masons
107  street_and_parking_lot_sweeper
108                       surveyors
109   telecommunication_technicians
110     telephone_line_construction
111                terrazzo_workers
112  tile_marble_terrazzo_finishers
113                    tile_setters
114        traffic_control_stripers
115                   truck_drivers
116         truck_drivers_ready_mix
117        well_drillers_irrigation

In [62]:
df_PWProjects.columns.tolist()

['project_id',
 'awarding_agency_name',
 'agency_category_type',
 'prime_contractor_name',
 'prime_contractor_ubi',
 'prime_intent_id',
 'project_name',
 'contract_number',
 '_apprentice_utilization_',
 'journeylevel_hours',
 'apprentice_hours',
 'total_hours',
 'apprentice_wages',
 'journeylevel_wages',
 'total_wages',
 'female_hours',
 'female_utilization_percentage',
 'minority_hours',
 'minority_utilization',
 'veteran_hours',
 'veteran_utilization_percentage',
 'asbestos_abatement_workers',
 'boilermakers',
 'bricklayers_marble_masons',
 'brick_and_marble_masons',
 'brick_mason',
 'building_service_employees',
 'cabinet_makers_in_shop',
 'carpenters',
 'cement_masons',
 'divers_tenders',
 'dredge_workers',
 'drywall_applicator',
 'drywall_tapers',
 'electrical_fixture_maintenance',
 'electricians_inside',
 'electricians_motor_shop',
 'electricians_powerline',
 'elevator_constructors',
 'electronic_technicians',
 'electronic_telecommunication',
 'fabricated_precast_concrete',
 'fence_erectors',
 'flaggers',
 'glaziers',
 'heat_frost_insulators_and',
 'heating_equipment_mechanics',
 'hod_carriers_mason_tenders',
 'industrial_engine_and_machine',
 'industrial_power_vacuum',
 'inland_boatmen',
 'inspection_cleaning_sealing',
 'inspection_cleaning_sealing_1',
 'insulation_applicators',
 'ironworkers',
 'laborers',
 'laborers_underground_sewer',
 'landscape_construction',
 'landscape_maintenance',
 'lathers',
 'machinists_hydroelectric',
 'marble_setters',
 'metal_fabrication_in_shop',
 'millwright',
 'modular_buildings',
 'painters',
 'pile_driver',
 'plasterers',
 'playground_park_equipment',
 'plumbers_pipefitters',
 'power_equipment_operators',
 'power_equipment_operators_1',
 'power_line_clearance_tree',
 'residential_brick_mason',
 'refrigeration_air_conditioning',
 'residential_drywall',
 'residential_brick_marble',
 'residential_carpenters',
 'residential_drywall_tapers',
 'residential_electricians',
 'residential_electronic',
 'residential_glaziers',
 'residential_insulation',
 'residential_laborers',
 'residential_cement_masons',
 'residential_marble_setters',
 'residential_stone_masons',
 'residential_painters',
 'residential_plumbers',
 'residential_refrigeration',
 'residential_sheet_metal',
 'residential_soft_floor_layers',
 'residential_sprinkler_fitters',
 'residential_terrazzo_tile',
 'residential_terrazzo_tile_1',
 'residential_tile_setters',
 'residential_terrazzo_workers',
 'roofers',
 'sheet_metal_workers',
 'shipbuilding_ship_repair',
 'sign_makers_installers',
 'sign_makers_installers_non',
 'soft_floor_layers',
 'solar_controls_for_windows',
 'sprinkler_fitters_fire',
 'stage_rigging_mechanics_non',
 'stone_masons',
 'street_and_parking_lot_sweeper',
 'surveyors',
 'telecommunication_technicians',
 'telephone_line_construction',
 'terrazzo_workers',
 'tile_marble_terrazzo_finishers',
 'tile_setters',
 'traffic_control_stripers',
 'truck_drivers',
 'truck_drivers_ready_mix',
 'well_drillers_irrigation']

In [45]:
# df_PWProjects.dtypes
df_PWProjects['awarding_agency_name'].unique()

array(['BELLEVUE, CITY OF', 'BELLEVUE, CITY OF/ PARKS & REC',
       'BELLEVUE, CITY OF/UTIL DEPT', 'BELLEVUE, CITY OF/ PUBLIC WORKS',
       'BELLEVUE, CITY OF/TRANS SVC'], dtype=object)

In [46]:
df_PWProjects[df_PWProjects['project_id'] == "1179276"]

,project_id,awarding_agency_name,agency_category_type,prime_contractor_name,prime_contractor_ubi,prime_intent_id,project_name,contract_number,_apprentice_utilization_,journeylevel_hours,apprentice_hours,total_hours,apprentice_wages,journeylevel_wages,total_wages,female_hours,female_utilization_percentage,minority_hours,minority_utilization,veteran_hours,veteran_utilization_percentage,asbestos_abatement_workers,boilermakers,bricklayers_marble_masons,brick_and_marble_masons,brick_mason,building_service_employees,cabinet_makers_in_shop,carpenters,cement_masons,divers_tenders,dredge_workers,drywall_applicator,drywall_tapers,electrical_fixture_maintenance,electricians_inside,electricians_motor_shop,electricians_powerline,elevator_constructors,electronic_technicians,electronic_telecommunication,fabricated_precast_concrete,fence_erectors,flaggers,glaziers,heat_frost_insulators_and,heating_equipment_mechanics,hod_carriers_mason_tenders,industrial_engine_and_machine,industrial_power_vacuum,inland_boatmen,inspection_cleaning_sealing,inspection_cleaning_sealing_1,insulation_applicators,ironworkers,laborers,laborers_underground_sewer,landscape_construction,landscape_maintenance,lathers,machinists_hydroelectric,marble_setters,metal_fabrication_in_shop,millwright,modular_buildings,painters,pile_driver,plasterers,playground_park_equipment,plumbers_pipefitters,power_equipment_operators,power_equipment_operators_1,power_line_clearance_tree,residential_brick_mason,refrigeration_air_conditioning,residential_drywall,residential_brick_marble,residential_carpenters,residential_drywall_tapers,residential_electricians,residential_electronic,residential_glaziers,residential_insulation,residential_laborers,residential_cement_masons,residential_marble_setters,residential_stone_masons,residential_painters,residential_plumbers,residential_refrigeration,residential_sheet_metal,residential_soft_floor_layers,residential_sprinkler_fitters,residential_terrazzo_tile,residential_terrazzo_tile_1,residential_tile_setters,residential_terrazzo_workers,roofers,sheet_metal_workers,shipbuilding_ship_repair,sign_makers_installers,sign_makers_installers_non,soft_floor_layers,solar_controls_for_windows,sprinkler_fitters_fire,stage_rigging_mechanics_non,stone_masons,street_and_parking_lot_sweeper,surveyors,telecommunication_technicians,telephone_line_construction,terrazzo_workers,tile_marble_terrazzo_finishers,tile_setters,traffic_control_stripers,truck_drivers,truck_drivers_ready_mix,well_drillers_irrigation
5867,1179276,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1524530,South Bellevue Station Neighborhood Improvements,25013,12.59,8432.95,1215,9647.95,64955.64,657002.8,721958.44,1747.25,18.11,2608.3,27.03,0,0,0,0,0,0,0,0,0,0,653.5,0,0,0,0,0,91.5,0,149,0,0,0,0,0,357,0,0,0,0,0,0,0,0,0,0,0,3812.5,0,158,0,0,0,0,0,0,0,0,0,0,0,0,3591.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100.5,0,0,0,0,0,0,620.9,113.55,0

In [47]:
df_PWProjects[df_PWProjects['prime_contractor_name'] == "KAMINS CONSTRUCTION INC"]
# df_PWProjects[df_PWProjects['contract_number'] == "25013"]

,project_id,awarding_agency_name,agency_category_type,prime_contractor_name,prime_contractor_ubi,prime_intent_id,project_name,contract_number,_apprentice_utilization_,journeylevel_hours,apprentice_hours,total_hours,apprentice_wages,journeylevel_wages,total_wages,female_hours,female_utilization_percentage,minority_hours,minority_utilization,veteran_hours,veteran_utilization_percentage,asbestos_abatement_workers,boilermakers,bricklayers_marble_masons,brick_and_marble_masons,brick_mason,building_service_employees,cabinet_makers_in_shop,carpenters,cement_masons,divers_tenders,dredge_workers,drywall_applicator,drywall_tapers,electrical_fixture_maintenance,electricians_inside,electricians_motor_shop,electricians_powerline,elevator_constructors,electronic_technicians,electronic_telecommunication,fabricated_precast_concrete,fence_erectors,flaggers,glaziers,heat_frost_insulators_and,heating_equipment_mechanics,hod_carriers_mason_tenders,industrial_engine_and_machine,industrial_power_vacuum,inland_boatmen,inspection_cleaning_sealing,inspection_cleaning_sealing_1,insulation_applicators,ironworkers,laborers,laborers_underground_sewer,landscape_construction,landscape_maintenance,lathers,machinists_hydroelectric,marble_setters,metal_fabrication_in_shop,millwright,modular_buildings,painters,pile_driver,plasterers,playground_park_equipment,plumbers_pipefitters,power_equipment_operators,power_equipment_operators_1,power_line_clearance_tree,residential_brick_mason,refrigeration_air_conditioning,residential_drywall,residential_brick_marble,residential_carpenters,residential_drywall_tapers,residential_electricians,residential_electronic,residential_glaziers,residential_insulation,residential_laborers,residential_cement_masons,residential_marble_setters,residential_stone_masons,residential_painters,residential_plumbers,residential_refrigeration,residential_sheet_metal,residential_soft_floor_layers,residential_sprinkler_fitters,residential_terrazzo_tile,residential_terrazzo_tile_1,residential_tile_setters,residential_terrazzo_workers,roofers,sheet_metal_workers,shipbuilding_ship_repair,sign_makers_installers,sign_makers_installers_non,soft_floor_layers,solar_controls_for_windows,sprinkler_fitters_fire,stage_rigging_mechanics_non,stone_masons,street_and_parking_lot_sweeper,surveyors,telecommunication_technicians,telephone_line_construction,terrazzo_workers,tile_marble_terrazzo_finishers,tile_setters,traffic_control_stripers,truck_drivers,truck_drivers_ready_mix,well_drillers_irrigation
64,937270,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1097952,NE 12th St Multipurpose Path 108th Ave NE to 1...,20061,4.99,3666.96,192.5,3859.46,8881.17,227407.03,236288.2,734.25,19.02,825.46,21.39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,466.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1320.5,0,710.5,0,0,0,0,0,0,0,0,0,0,0,0,1146.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,0,0,0,0,0,10,169.25,11.96,0
87,886868,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,990953,Tyee Middle School Safety Project,19028,0,12.5,0,12.5,0,716.6,716.6,0,0,7.5,60,5,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12.5,0,0
247,940952,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1105211,124th Ave NE - NE 8th St to NE 12th St Safety ...,20028,0,2439.52,0,2439.52,0,156292.69,156292.69,931.5,38.18,182.77,7.49,8,0.33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,107,0,412,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,885,0,0,0,0,0,0,0,0,0,0,0,0,0,0,896,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35.5,0,0,0,0,0,59.5,15.25,22.27,0
474,968435,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1155972,105th Ave SE Sidewalk SE Wolverine Way to Main...,21001,1.59,2814.5,45.5,2860,2513.87,181899.65,184413.52,468.75,16.39,444,15.52,0,0,0,0,0,0,0,0,0,0,171.5,0,0,0,0,0,109,0,52,0,0,0,0,0,330.5,0,0,0,0,0,0,0,0,0,0,0,869,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1119,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36.5,0,0,0,0,0,49.75,122.75,0,0
539,916466,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1052927,SE 16th Street Walkway,20022,0.33,1489.5,5,1494.5,195.9,89097.48,89293.38,316.5,21.18,216.5,14.49,3.5,0.23,0,0,0,0,0,0,0,0,103.5,0,0,0,0,0,141,0,212,0,0,0,0,0,196,0,0,0,0,0,0,0,0,0,0,0,333,0,0,0,0,0,0,0,0,0,0,0,0,0,0,422.75,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33,0,0,0,0,0,12.5,20.75,0,0
581,978497,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1176021,2021 Citywide Crosswalk Improvements,21084,0.51,2066.71,10.5,2077.21,468.92,136013.25,136482.17,402,19.35,288.97,13.91,0,0,0,0,0,0,0,0,0,0,71,0,0,0,0,0,539,0,398,0,0,0,0,0,196.5,0,0,0,0,0,0,0,0,0,0,0,488,0,0,0,0,0,0,0,0,0,0,0,0,0,0,322.25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,29.5,0,0,0,0,0,6,19.5,7.46,0
760,907444,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1036693,Downtown Park Median Expansions and Crossings,19095,0,1248.15,0,1248.15,0,75738.66,75738.66,175,14.02,214.92,17.22,40,3.2,0,0,0,0,0,0,0,0,127.5,0,0,0,0,0,40,0,0,0,0,0,0,0,131.5,0,0,0,0,0,0,0,0,0,0,0,425,0,0,0,0,0,0,0,0,0,0,0,0,0,0,445.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23.75,0,0,0,0,0,12.5,0,42.15,0
997,999678,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1211709,2022 Crosswalk Improvements,22006,5.38,5582.44,317.5,5899.94,21279.99,370089.23,391369.22,1342.5,22.75,608.5,10.31,220,3.73,0,0,0,0,0,0,0,0,317,0,0,0,0,0,870,0,0,0,0,0,0,0,951,0,0,0,0,0,0,0,0,0,0,0,1974.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1593.1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,79.5,0,0,0,0,0,50,33.25,31.59,0
4615,1131132,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1439942,SE 54th Pl and SE 52nd St Sidewalks,24016,0.99,1199.15,12,1211.15,626.28,90580.17,91206.45,306.75,25.33,224.25,18.52,0,0,0,0,0,0,0,0,0,0,119.5,0,0,0,0,0,0,0,0,0,0,0,0,0,136.5,0,0,0,0,0,0,0,0,0,0,0,265.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,560.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,96.5,30.65,0
4674,1096917,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1381930,Main Street Crosswalk Improvements,23087,0,546.25,0,546.25,0,45299.89,45299.89,259,47.41,165.75,30.34,0,0,0,0,0,0,0,0,0,0,15.5,0,0,0,0,0,264,0,60.5,0,0,0,0,2.25,3.5,0,0,0,0,0,0,0,0,0,0,0,112.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4678,1025874,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1256784,Lake Hills Blvd & 148th Ave SE Intersection Im...,22036,1.57,2669.96,42.5,2712.46,2523.25,187197.83,189721.08,463.5,17.09,490.64,18.09,4,0.15,0,0,0,0,0,0,0,0,123.5,0,0,0,0,0,308,0,224,0,0,0,0,178.25,55.5,0,0,0,0,0,0,0,0,0,0,0,816.75,0,70,0,0,0,0,0,0,0,0,0,0,0,0,773,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.25,0,0,0,0,0,43.5,53.5,16.21,0
5369,1143010,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1462983,2024 ADA Curb Ramp Improvements,24069,0,1366.75,0,1366.75,0,105041.09,105041.09,301.5,22.06,264.75,19.37,0,0,0,0,0,0,0,0,0,0,186,0,0,0,0,0,9,0,14,0,0,0,0,0,93.5,0,0,0,0,0,0,0,0,0,0,0,533,0,0,0,0,0,0,0,0,0,0,0,0,0,0,505.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,11.75,0
5422,1086860,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1362965,2022 RRFB Crosswalk Improvements,23028,2.35,1391.85,33.5,1425.35,1636.67,110581.69,112218.36,543,38.1,366.1,25.68,0,0,0,0,0,0,0,0,0,0,74,0,0,0,0,0,498,0,20,0,0,0,0,0,54.5,0,0,0,0,0,0,0,0,0,0,0,430.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,303.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,7,16.5,10.1,0
5867,1179276,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1524530,South Bellevue Station Neighborhood Improvements,25013,12.59,8432.95,1215,9647.95,64955.64,657002.8,721958.44,1747.25,18.11,2608.3,27.03,0,0,0,0,0,0,0,0,0,0,653.5,0,0,0,0,0,91.5,0,149,0,0,0,0,0,357,0,0,0,0,0,0,0,0,0,0,0,3812.5,0,158,0,0,0,0,0,0,0,0,0,0,0,0,3591.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100.5,0,0,0,0,0,0,620.9,113.55,0

In [48]:
df_PWProjects.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Columns: 118 entries, project_id to well_drillers_irrigation
dtypes: object(118)
memory usage: 5.4+ MB

In [49]:
df_PWProjects[df_PWProjects['contract_number'].isin(["25013","25010", "24120", "24000", "24006", "24011"])]

,project_id,awarding_agency_name,agency_category_type,prime_contractor_name,prime_contractor_ubi,prime_intent_id,project_name,contract_number,_apprentice_utilization_,journeylevel_hours,apprentice_hours,total_hours,apprentice_wages,journeylevel_wages,total_wages,female_hours,female_utilization_percentage,minority_hours,minority_utilization,veteran_hours,veteran_utilization_percentage,asbestos_abatement_workers,boilermakers,bricklayers_marble_masons,brick_and_marble_masons,brick_mason,building_service_employees,cabinet_makers_in_shop,carpenters,cement_masons,divers_tenders,dredge_workers,drywall_applicator,drywall_tapers,electrical_fixture_maintenance,electricians_inside,electricians_motor_shop,electricians_powerline,elevator_constructors,electronic_technicians,electronic_telecommunication,fabricated_precast_concrete,fence_erectors,flaggers,glaziers,heat_frost_insulators_and,heating_equipment_mechanics,hod_carriers_mason_tenders,industrial_engine_and_machine,industrial_power_vacuum,inland_boatmen,inspection_cleaning_sealing,inspection_cleaning_sealing_1,insulation_applicators,ironworkers,laborers,laborers_underground_sewer,landscape_construction,landscape_maintenance,lathers,machinists_hydroelectric,marble_setters,metal_fabrication_in_shop,millwright,modular_buildings,painters,pile_driver,plasterers,playground_park_equipment,plumbers_pipefitters,power_equipment_operators,power_equipment_operators_1,power_line_clearance_tree,residential_brick_mason,refrigeration_air_conditioning,residential_drywall,residential_brick_marble,residential_carpenters,residential_drywall_tapers,residential_electricians,residential_electronic,residential_glaziers,residential_insulation,residential_laborers,residential_cement_masons,residential_marble_setters,residential_stone_masons,residential_painters,residential_plumbers,residential_refrigeration,residential_sheet_metal,residential_soft_floor_layers,residential_sprinkler_fitters,residential_terrazzo_tile,residential_terrazzo_tile_1,residential_tile_setters,residential_terrazzo_workers,roofers,sheet_metal_workers,shipbuilding_ship_repair,sign_makers_installers,sign_makers_installers_non,soft_floor_layers,solar_controls_for_windows,sprinkler_fitters_fire,stage_rigging_mechanics_non,stone_masons,street_and_parking_lot_sweeper,surveyors,telecommunication_technicians,telephone_line_construction,terrazzo_workers,tile_marble_terrazzo_finishers,tile_setters,traffic_control_stripers,truck_drivers,truck_drivers_ready_mix,well_drillers_irrigation
4551,1115490,"BELLEVUE, CITY OF",City,LAKESIDE INDUSTRIES INC,601106847,1416325,2024 Overlay Program,24000,17.08,27101.51,5580.5,32682.01,303777.19,1938577.72,2242354.91,6143,18.8,22156.4,67.79,488.28,1.49,0,0,0,0,0,0,0,0,1498.5,0,0,0,0,0,79,0,115,0,0,0,0,0,7582,0,0,0,0,0,0,0,0,0,0,0,10398.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6519.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,251.5,0,0,0,0,0,429.5,5663.24,145.02,0
5383,1125236,"BELLEVUE, CITY OF",City,NORTHWEST CASCADE INC,278049149,1429264,123rd Ave SE Improvements (SE 60 St to Newcast...,24011,15.34,13481.07,2443.5,15924.57,119758.92,943160.97,1062919.89,2314.25,14.53,7246.75,45.51,328.25,2.06,0,0,0,0,0,0,0,0,1042.5,0,0,0,0,0,75,0,41,0,0,0,0,61,5723,0,0,0,0,0,0,0,0,0,0,0,3341.5,0,206,0,0,0,0,0,0,0,0,0,0,0,0,4174.6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,47.5,0,0,0,0,0,73.5,1009.67,129.3,0
5768,1134725,"BELLEVUE, CITY OF",City,R C N W,602286010,1446222,156th Ave & Main St and 156th Ave SE & Lk Hill...,24006,15.25,11810.58,2125.5,13936.08,119496.75,787751.38,907248.13,3977,28.54,4558.89,32.71,44,0.32,0,0,0,0,0,0,0,0,309.5,0,0,0,0,0,1439.5,0,666.5,0,0,0,0,0,4936.25,0,0,0,0,0,0,0,0,0,0,2.5,4775.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,836,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,29.5,0,208.05,0,0,0,66.75,587.25,78.53,0
5867,1179276,"BELLEVUE, CITY OF",City,KAMINS CONSTRUCTION INC,603459120,1524530,South Bellevue Station Neighborhood Improvements,25013,12.59,8432.95,1215,9647.95,64955.64,657002.8,721958.44,1747.25,18.11,2608.3,27.03,0,0,0,0,0,0,0,0,0,0,653.5,0,0,0,0,0,91.5,0,149,0,0,0,0,0,357,0,0,0,0,0,0,0,0,0,0,0,3812.5,0,158,0,0,0,0,0,0,0,0,0,0,0,0,3591.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100.5,0,0,0,0,0,0,620.9,113.55,0
5888,1174558,"BELLEVUE, CITY OF",City,GRANITE CONSTRUCTION COMPANY,409023062,1516412,NE 8TH ST AND I-405 CROSSING IMPROVEMENTS AND ...,24120,15.34,5352.79,970,6322.79,57112.41,411982.64,469095.05,638.5,10.1,5527.1,87.42,8.5,0.13,0,0,0,0,0,0,0,0,328,0,0,0,0,0,419,0,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3698.25,0,472,92,0,0,0,0,0,0,0,0,0,0,0,634,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,84.5,0,0,0,0,0,62,453.75,39.29,0
5988,1177553,"BELLEVUE, CITY OF",City,PIVETTA BROTHERS CONST INC,600522209,1524726,150th Avenue SE Mobility Project,25010,17.13,15185.66,3138.11,18323.77,171163.79,1282731,1453894.79,3209.25,17.51,5847.51,31.91,31.09,0.17,18,0,0,0,0,0,0,401,368,0,0,0,0,0,2517,0,925,0,0,0,0,4,249.5,0,0,0,0,0,0,0,0,4,0,64,5675.53,2099.5,0,0,0,0,0,0,0,0,0,0,0,0,0,1139.67,3001.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,176.5,0,27.5,0,0,0,0,1572.25,80.57,0